-- 5. Creating a View to Report Revenue Generated by Employees Through Ticket Issuance
CREATE VIEW View_Employee_Issued_Tickets_Revenue AS
SELECT e.employee_id, e.first_name + ' ' + e.last_name AS employee_name,  -- Concatenates first and last name of the employee
f.flight_id, f.flight_number,t.eboarding_number,t.fare,
 -- If baggage exists, include its fee; otherwise, treat as 0
    ISNULL(b.baggage_fee, 0) AS baggage_fee,
	-- If meal is upgraded, add fee of 20; else 0
    CASE WHEN m.upgraded_meal = 1 THEN 20 ELSE 0 END AS meal_fee,
	-- If seat is preferred, add fee of 30; else 0
    CASE WHEN s.preferred_seat = 1 THEN 30 ELSE 0 END AS seat_fee,
	-- If seat is preferred, add fee of 30; else 0
    t.fare + ISNULL(b.baggage_fee, 0) +
    CASE WHEN m.upgraded_meal = 1 THEN 20 ELSE 0 END +
    CASE WHEN s.preferred_seat = 1 THEN 30 ELSE 0 END AS total_revenue
FROM Tickets t
INNER JOIN Ticket_Issuance ti ON t.ticket_issuance_id = ti.ticket_issuance_id
INNER JOIN Employees e ON ti.employee_id = e.employee_id
INNER JOIN Payments pay ON ti.payment_id = pay.payment_id
INNER JOIN PNR pnr ON pay.pnr_id = pnr.pnr_id
INNER JOIN Reservations r ON r.reservation_id = pnr.reservation_id
INNER JOIN Flights f ON r.flight_id = f.flight_id
LEFT JOIN Meals m ON r.meal_id = m.meal_id
LEFT JOIN Baggage b ON r.baggage_id = b.baggage_id
LEFT JOIN Seats s ON r.seat_id = s.seat_id;
SELECT * FROM View_Employee_Issued_Tickets_Revenue WHERE employee_id = 2;

-- 7. Creating a View to Return the Total Number of Checked-In Baggages for Each Flight
CREATE VIEW View_CheckedIn_Baggage_Count AS
SELECT
    f.flight_id,
    f.flight_number,
    r.reservation_date,
	-- Count the number of baggage items that have been checked in for each flight
    COUNT(b.baggage_id) AS checked_in_baggage_count
FROM
    Flights f
INNER JOIN Reservations r ON f.flight_id = r.flight_id
INNER JOIN Baggage b ON r.baggage_id = b.baggage_id
WHERE
    b.check_in_status = 'Checked_in'
-- Group results by flight details and reservation date to get total checked-in baggage count for each flight
GROUP BY
    f.flight_id, f.flight_number, r.reservation_date;
SELECT *
FROM View_CheckedIn_Baggage_Count
WHERE flight_id = 201 AND reservation_date = '2025-04-24';
